### ISSUE TITLE
Dashes in filenames become directories when installed

### ISSUE THREAD

**Issue by GUI** [openresty/opm#33]
I just tried adding an existing package of mine, [lua-libcidr-ffi](https://github.com/GUI/lua-libcidr-ffi), to OPM. But I hit one oddity after uploading and then installing the package, and I wasn't sure if it was a bug or intended behavior.

Inside the package, there's currently a `lib/libcidr-ffi.lua` file. So under the current LuaRock's based installation approach, you require this file via `require "libcidr-ffi"`. However, after uploading the package to OPM and then installing it (via `opm get GUI/lua-libcidr-ffi`), it looks like OPM placed the lib file in a slightly different location. Instead of installing a `libcidr-ffi.lua` file that could be required, it instead installed the file into `site/lualib/libcidr/ffi.lua`. So it looks like the dash in the filename somehow got translated to a parent directory during installation. This means the require statement under OPM has to be changed to `require "libcidr.ffi"`.

Of possible note, it looks like the files got uploaded retaining the original filename structure:

```
$ opm upload
found license: MIT license.
extracted verson number 0.1.1 from main_module file lib/libcidr-ffi.lua.
lua-libcidr-ffi-0.1.1/
lua-libcidr-ffi-0.1.1/dist.ini
lua-libcidr-ffi-0.1.1/lib/
lua-libcidr-ffi-0.1.1/lib/libcidr-ffi.lua
lua-libcidr-ffi-0.1.1/README.md
```

So it seems like this directory translation is only happening at install time.

From my perspective, it seems like it might be more intuitive and less surprising if the original filenames could be retained during installation. However, if this directory translation is intended behavior under OPM, I can rename things in my repo to have a consistent installation between both OPM and LuaRocks.

But overall, the process to upload a new OPM package was super easy, and I'm excited to see OPM released. Thanks!

**Comment by agentzh** [comment]
@GUI I recall that this issue has been fixed in opm recently. Are you using the latest version of opm script in the github repos?

**Comment by GUI** [comment]
@agentzh: Ah, sorry for not including that information. Yesterday, I was using the version bundled with the new OpenResty 1.11.2.2 RC1 release. I just tried with the latest version from master ([74f39e5](https://github.com/openresty/opm/blob/74f39e5e0b5633789f92472e2df5da04e6d15b91/bin/opm), which appears to the be same version bundled with 1.11.2.2 RC1), and I'm still seeing the same issue.

It actually looks like the issue might be with how the tar file is being created on upload (or how it's delivered from the server). If I download the raw tar.gz file that's used for the installation, it looks like the file has been renamed inside that archive (the file is stored as `lib/libcidr/ffi.lua` versus the `lib/libcidr-ffi.lua` filename reported during `opm upload`):

```sh
$ curl -OLs "https://opm.openresty.org/api/pkg/tarball/GUI/lua-libcidr-ffi-0.1.1.opm.tar.gz"
$ tar -xvf lua-libcidr-ffi-0.1.1.opm.tar.gz
x lua-libcidr-ffi-0.1.1.opm/
x lua-libcidr-ffi-0.1.1.opm/README.md
x lua-libcidr-ffi-0.1.1.opm/resty.index
x lua-libcidr-ffi-0.1.1.opm/lib/
x lua-libcidr-ffi-0.1.1.opm/lib/libcidr/
x lua-libcidr-ffi-0.1.1.opm/lib/libcidr/ffi.lua
x lua-libcidr-ffi-0.1.1.opm/pod/
x lua-libcidr-ffi-0.1.1.opm/pod/lua-libcidr-ffi-0.1.1/
x lua-libcidr-ffi-0.1.1.opm/pod/lua-libcidr-ffi-0.1.1/lua-libcidr-ffi-0.1.1.pod
x lua-libcidr-ffi-0.1.1.opm/dist.ini
````

**Comment by agentzh** [comment]
@GUI It seems that the opm server was running an old version of `opm-pkg-indexer.pl` daemon. I've just restarted that deamon using the latest opm repo. Please retry uploading. Thanks for the report!

**Comment by GUI** [comment]
Thanks. I just tried uploading a new version, but it looks like dashes are still being converted into directories. Here's the log output of the upload (at 2016-11-07 01:51 UTC):

```
$ opm upload
found license: MIT license.
extracted verson number 0.1.2 from main_module file lib/libcidr-ffi.lua.
lua-libcidr-ffi-0.1.2/
lua-libcidr-ffi-0.1.2/dist.ini
lua-libcidr-ffi-0.1.2/lib/
lua-libcidr-ffi-0.1.2/lib/libcidr-ffi.lua
lua-libcidr-ffi-0.1.2/README.md
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Mon, 07 Nov 2016 01:51:48 GMT
Server: openresty
Content-Length: 139
Connection: keep-alive

File lua-libcidr-ffi-0.1.2.tar.gz has been successfully uploaded and will be processed by the server shortly.
The uploaded task ID is 129.
```

And here's the new tar.gz that still returning the file as `libcidr/ffi.lua`:

```
$ curl -OLs "https://opm.openresty.org/api/pkg/tarball/GUI/lua-libcidr-ffi-0.1.2.opm.tar.gz"
$ tar -xvf lua-libcidr-ffi-0.1.2.opm.tar.gz 
lua-libcidr-ffi-0.1.2.opm/
lua-libcidr-ffi-0.1.2.opm/README.md
lua-libcidr-ffi-0.1.2.opm/resty.index
lua-libcidr-ffi-0.1.2.opm/lib/
lua-libcidr-ffi-0.1.2.opm/lib/libcidr/
lua-libcidr-ffi-0.1.2.opm/lib/libcidr/ffi.lua
lua-libcidr-ffi-0.1.2.opm/pod/
lua-libcidr-ffi-0.1.2.opm/pod/lua-libcidr-ffi-0.1.2/
lua-libcidr-ffi-0.1.2.opm/pod/lua-libcidr-ffi-0.1.2/lua-libcidr-ffi-0.1.2.pod
lua-libcidr-ffi-0.1.2.opm/dist.ini
```

Thanks for looking into this!

**Comment by agentzh** [comment]
@GUI Sorry, I forgot to update the `opm` script on the opm package server. I only updated the `opm-pkg-indexer.pl` script there. I've just tested against the opm.openresty.org server myself and it should work now. Please try again. Sorry for the inconvenience!

**Comment by GUI** [comment]
@agentzh: No worries, thanks for taking the time to debug this. And it looks like your last update worked. I was able to upload v0.1.3 and it retains the `libcidr-ffi.lua` filename on download. Thanks again!
